Console.log ("Rodando o sistema de gerenciamento de jogos")
Console.log("Aplicação conectando ao banco de dados")
console.log("Alteração 1")
console.log("Alteração 2")
console.log("Alteração 3")
console.log("Alteração 4")
console.log("Enviando para o GitHub - curso")
console.log("Log do Robson")
console.log("Log do SIRES")
